### ISSUE TITLE
./tests/LeakyVaccine/LeakyVaccine_failed_to_fully_load.log

### ISSUE THREAD

**Issue by menriquez-IDM** [menriquez-IDM/OnlineEcosystemMon#43]
# Issue Report:
        
## Property Site:
https://leakyvaccine.bmgf.io/ 
        
### Title:        
LeakyVaccine failed to fully load
        
## Exception Type:
NoSuchElementException
        
## Exception Message: 
```
Message: no such element: Unable to locate element: {"method":"css selector","selector":"rect[data-subplot='x2y']"}
  (Session info: headless chrome=115.0.5790.110); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x5567b34d34e3 <unknown>
#1 0x5567b3202c76 <unknown>
#2 0x5567b323ec96 <unknown>
#3 0x5567b323edc1 <unknown>
#4 0x5567b32787f4 <unknown>
#5 0x5567b325e03d <unknown>
#6 0x5567b327630e <unknown>
#7 0x5567b325dde3 <unknown>
#8 0x5567b32332dd <unknown>
#9 0x5567b323434e <unknown>
#10 0x5567b34933e4 <unknown>
#11 0x5567b34973d7 <unknown>
#12 0x5567b34a1b20 <unknown>
#13 0x5567b3498023 <unknown>
#14 0x5567b34661aa <unknown>
#15 0x5567b34bc6b8 <unknown>
#16 0x5567b34bc847 <unknown>
#17 0x5567b34cc243 <unknown>
#18 0x7f6a6e85cea7 start_thread

```
        
## Traceback:       
```
Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/menriquez/LiveSitesMonitoringNightly/tests/LeakyVaccine/Test_LeakyVaccine.py", line 39, in <module>
    plotx2y = driver.find_element(By.CSS_SELECTOR, "rect[data-subplot='x2y']")
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 740, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"rect[data-subplot='x2y']"}
  (Session info: headless chrome=115.0.5790.110); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x5567b34d34e3 <unknown>
#1 0x5567b3202c76 <unknown>
#2 0x5567b323ec96 <unknown>
#3 0x5567b323edc1 <unknown>
#4 0x5567b32787f4 <unknown>
#5 0x5567b325e03d <unknown>
#6 0x5567b327630e <unknown>
#7 0x5567b325dde3 <unknown>
#8 0x5567b32332dd <unknown>
#9 0x5567b323434e <unknown>
#10 0x5567b34933e4 <unknown>
#11 0x5567b34973d7 <unknown>
#12 0x5567b34a1b20 <unknown>
#13 0x5567b3498023 <unknown>
#14 0x5567b34661aa <unknown>
#15 0x5567b34bc6b8 <unknown>
#16 0x5567b34bc847 <unknown>
#17 0x5567b34cc243 <unknown>
#18 0x7f6a6e85cea7 start_thread


```
        
## Date:            
2023-07-27 15:41:13.495119

**Comment by menriquez-IDM** [comment]
Not repro.
