### ISSUE TITLE
./tests/LeakyVaccine/LeakyVaccine_failed_to_fully_load.log

### ISSUE THREAD

**Issue by menriquez-IDM** [menriquez-IDM/OnlineEcosystemMon#45]
# Issue Report:
        
## Property Site:
https://leakyvaccine.bmgf.io/ 
        
### Title:        
LeakyVaccine failed to fully load
        
## Exception Type:
NoSuchElementException
        
## Exception Message: 
```
Message: no such element: Unable to locate element: {"method":"css selector","selector":"rect[data-subplot='x2y']"}
  (Session info: headless chrome=115.0.5790.110); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55f9f05cc4e3 <unknown>
#1 0x55f9f02fbc76 <unknown>
#2 0x55f9f0337c96 <unknown>
#3 0x55f9f0337dc1 <unknown>
#4 0x55f9f03717f4 <unknown>
#5 0x55f9f035703d <unknown>
#6 0x55f9f036f30e <unknown>
#7 0x55f9f0356de3 <unknown>
#8 0x55f9f032c2dd <unknown>
#9 0x55f9f032d34e <unknown>
#10 0x55f9f058c3e4 <unknown>
#11 0x55f9f05903d7 <unknown>
#12 0x55f9f059ab20 <unknown>
#13 0x55f9f0591023 <unknown>
#14 0x55f9f055f1aa <unknown>
#15 0x55f9f05b56b8 <unknown>
#16 0x55f9f05b5847 <unknown>
#17 0x55f9f05c5243 <unknown>
#18 0x7f08c1c79ea7 start_thread

```
        
## Traceback:       
```
Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/menriquez/LiveSitesMonitoringNightly/tests/LeakyVaccine/Test_LeakyVaccine.py", line 39, in <module>
    plotx2y = driver.find_element(By.CSS_SELECTOR, "rect[data-subplot='x2y']")
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 740, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"rect[data-subplot='x2y']"}
  (Session info: headless chrome=115.0.5790.110); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55f9f05cc4e3 <unknown>
#1 0x55f9f02fbc76 <unknown>
#2 0x55f9f0337c96 <unknown>
#3 0x55f9f0337dc1 <unknown>
#4 0x55f9f03717f4 <unknown>
#5 0x55f9f035703d <unknown>
#6 0x55f9f036f30e <unknown>
#7 0x55f9f0356de3 <unknown>
#8 0x55f9f032c2dd <unknown>
#9 0x55f9f032d34e <unknown>
#10 0x55f9f058c3e4 <unknown>
#11 0x55f9f05903d7 <unknown>
#12 0x55f9f059ab20 <unknown>
#13 0x55f9f0591023 <unknown>
#14 0x55f9f055f1aa <unknown>
#15 0x55f9f05b56b8 <unknown>
#16 0x55f9f05b5847 <unknown>
#17 0x55f9f05c5243 <unknown>
#18 0x7f08c1c79ea7 start_thread


```
        
## Date:            
2023-07-31 20:16:18.976126

**Comment by menriquez-IDM** [comment]
NO REPRO
